name: User Story Validator
description: A user story validation plugin that assesses and validate user story compliance in codebases
author: https://github.com/YuchenCAO01
requirements: []
configuration:
  properties:
    userStoriesFile:
      type: string
  additionalProperties: false

commands:
  pre-command:
    - label: "Validating User Stories Syntax"
      plugins:
        - docker#v3.8.0:
            image: "python:3.9"
            mount-buildkite-agent: false
            workdir: /app
            command: ["hooks/pre-command"]
