name: User Story Validator
description: A user story validation plugin that assesses and validate user story compliance in codebases
author: https://github.com/YuchenCAO01
requirements: []
configuration:
  properties:
    userStoriesFile:
      type: string
  additionalProperties: false