#!/bin/bash
echo 'version 0.0.2'
echo "executing the command hook"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "$DIR"

# echo "${BASH_SOURCE[0]}"

echo "checking user story templates"

python "$DIR/../scripts/python/validate-user-stories.py" "./buildkite/$USER_STORIES_FILE"