#!/bin/bash
echo "executing the command hook"

# DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "${BASH_SOURCE[0]}"

echo "checking user story templates"

python "../scripts/python/validate-user-stories.py" "./buildkite/$USER_STORIES_FILE"