#!/bin/bash
echo 'version 0.0.2'
echo "executing the command hook"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "$DIR"

# echo "${BASH_SOURCE[0]}"

echo "checking user story templates"
USER_STORIES_FILE=${BUILDKITE_PLUGIN_USER_STORY_VALIDATION_PLUGIN_MAPPING_FILE:-"user-stories.yml"}
python "$DIR/../scripts/python/validate-user-stories.py" "$USER_STORIES_FILE"