#!/bin/bash

set -euo pipefail
echo 'version 0.0.2'
echo "pre-command start"

# Check the environment and install dependencies if needed
# Check if Python is installed
if ! command -v python &> /dev/null; then
    echo "Python is not installed. Please use a docker have python"
    # Add Python installation commands here (depends on the environment)
    

fi

echo "env check finished"

echo "check user story files"
# Get the user stories file path from plugin configuration
USER_STORIES_FILE=${BUILDKITE_PLUGIN_USER_STORY_VALIDATION_PLUGIN_MAPPING_FILE:-"user-stories.yml"}


