#!/bin/bash

set -euo pipefail

# Define working directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "pre-command start"

# Check the environment and install dependencies if needed
bash "$DIR/scripts/shell/check-environment.sh"
echo "env check finished"

echo "check user story files"
# Get the user stories file path from plugin configuration
USER_STORIES_FILE=${BUILDKITE_PLUGIN_USER_STORY_VALIDATION_PLUGIN_MAPPING_FILE:-"user-stories.yml"}

echo "checking user story templates"
# Validate the user stories
python "$DIR/scripts/python/validate-user-stories.py" "./buildkite/$USER_STORIES_FILE"
